# https://docs.github.com/en/actions/tutorials/build-and-test-code/nodejs#example-using-yarn
# https://github.com/actions/setup-node
name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:  # Currently Node.js [20.x, 22.x, 24.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [lts/-2, lts/-1, lts/*]
        exclude:
          - os: ubuntu-latest
            node-version: lts/*
    runs-on: ${{ matrix.os }}
    steps:
      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxtst-dev
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'yarn'
      - run: yarn
      # - run: yarn test
      # - run: node test/test.js
      # - run: node test/active.js
      # - run: node test/all.js
      # - run: node test/bounds.js
      # - run: node test/click.js
      # - run: node test/focus.js
      # - run: node test/keyboard.js
      # - run: node test/running.js
      # - run: node test/state.js
