# https://docs.github.com/en/actions/tutorials/build-and-test-code/nodejs#example-using-yarn
# https://github.com/actions/setup-node
name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        node-version: [lts/*, lst/-1, lts/-2]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      # - run: yarn test
      - run: node test/test.js
